PREFIX mdw: <http://interiot.eu/ont/middleware.owl#>
PREFIX clients: <http://interiot.eu/clients#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
ASK {
  GRAPH <http://inter-iot.eu/clients> {
    ?clientId rdf:type ?clientGraph
  }
}