PREFIX mdw: <http://interiot.eu/ont/middleware.owl#>
PREFIX clients: <http://interiot.eu/clients#>

DELETE WHERE {
  GRAPH <http://inter-iot.eu/devices> {
    ?deviceId ?p ?o
  }
};

DROP GRAPH ?deviceId
