PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX sf: <http://www.opengis.net/ont/sf#>

DELETE WHERE {
    GRAPH <http://inter-iot.eu/location_points> {
        ?locationId ?p ?o;
            geo:hasGeometry ?geo .
        ?geo rdf:type sf:Point;
            geo:asWKT ?point .
    }
};
