PREFIX mdw: <http://interiot.eu/ont/middleware.owl#>
PREFIX clients: <http://interiot.eu/clients#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?locationId ?description ?latitude ?longitude
WHERE {
GRAPH ?locationGraphId
{
          ?locationId mdw:description ?description;
                    OPTIONAL { ?locationId mdw:hasLatitude ?latitude; }
                    OPTIONAL { ?locationId mdw:hasLongitude ?longitude; }
	}
}