PREFIX mdw: <http://interiot.eu/ont/middleware.owl#>
PREFIX clients: <http://interiot.eu/clients#>
PREFIX subscriptions: <http://interiot.eu/subscriptions#>
DELETE WHERE {
  GRAPH <http://inter-iot.eu/plat2plat-subscriptions> {
    ?conversationId ?p1 ?o1
  }
}
